export enum EstrategiaActividadEstadoEnum {
  PENDIENTE = 'PENDIENTE',
  EN_PROGRESO = 'EN_PROGRESO',
  EN_REVISION = 'EN_REVISION',
  EN_EJECUCION = 'EN_EJECUCION',
  FINALIZADO = 'FINALIZADO',
  PARALIZADO = 'PARALIZADO',
  COMPLETADO = 'COMPLETADO',
}
